apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-server
        image: devinwrogers/thesis-myapp:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

        # docker build -t devinwrogers/thesis-myapp:latest ./myapp
        # docker login
        # docker push devinwrogers/thesis-myapp:latest

        # kubectl apply -f ./k8/deployment.yaml
        # check if deployment worked/pod is running (kubectl get deployment, pods)
        # kubectl apply -f ./k8/service.yaml (usually not needed)
        # check for service (kubectl get svc)
        # minikube service myapp-service (this will open website on localhost)


        # IF DEPLOYMENT/SERVICE ALREADY APPLIED...
        # docker build, login, then push
        # delete current pods
        # minikube service myapp-service
        
